CREATE TABLE USERS(
	USER_ID    INT PRIMARY KEY AUTO_INCREMENT,
	USER_NAME   VARCHAR(30) NOT NULL,
	FIRST_NAME   VARCHAR(30) NOT NULL,
	LAST_NAME    VARCHAR(30) NOT NULL,
	EMAIL        VARCHAR(30) NULL,
	CREATE_USERID  INT,
	CREATE_TIMESTAMP TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
	UPDATE_USERID   INT,
	UPDATE_TIMESTAMP TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00'
);


CREATE TABLE PERSONS (
  PERSON_ID INT PRIMARY KEY AUTO_INCREMENT,
  FIRST_NAME varchar(30) NOT NULL,
  LAST_NAME varchar(30) NOT NULL
);

-------------------------------------------------------------------------------------------

CREATE TABLE EMPLOYEES
(
    ID          INT PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME   VARCHAR(30),
    LASTNAME    VARCHAR(30),
    TELEPHONE   VARCHAR(15),
    EMAIL       VARCHAR(30),
    CREATED     TIMESTAMP DEFAULT NOW()
);


-------------------------------------------------------------------------------------------
CREATE TABLE CUSTOMERS(
	CUSTOMER_ID      INT NOT NULL AUTO_INCREMENT,
	NAME             VARCHAR(30) NOT NULL,
	ADDRESS          VARCHAR(30) NULL,
	PHONE_NUMBER     VARCHAR(30) NULL,
	EMAIL            VARCHAR(30) NULL,
	COUNTRY          VARCHAR(30) NULL,
	CITY             VARCHAR(30) NULL,	
	CREATE_USERID    INT,
	CREATE_TIMESTAMP TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
	UPDATE_USERID    INT,
	UPDATE_TIMESTAMP TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY(CUSTOMER_ID)	
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

CREATE TABLE ORDERS(
	ORDER_ID         INT NOT NULL AUTO_INCREMENT,
	ORDER_DATE	     TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	DELIVERY_DATE    TIMESTAMP NULL DEFAULT NULL,
	PAYMENT_METHOD   VARCHAR(10) NOT NULL DEFAULT 'CASH',
	STATUS           VARCHAR(10) NOT NULL DEFAULT 'PAID',
	DISCOUNT         NUMERIC NULL DEFAULT 0,
	ORDER_TOTAL      NUMERIC NULL DEFAULT 0,
	CUSTOMER_ID      INT NULL,
	CREATE_USERID    INT,
	CREATE_TIMESTAMP TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
	UPDATE_USERID    INT,
	UPDATE_TIMESTAMP TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY(ORDER_ID),
	INDEX FK_CUSTOMER (CUSTOMER_ID),
	CONSTRAINT FK_CUSTOMER FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

CREATE TABLE ITEMS(
	ITEM_ID    	BIGINT PRIMARY KEY AUTO_INCREMENT,
	PRODUCT_NAME   	VARCHAR(30) NOT NULL,
	PRICE   	DECIMAL(10,2) NULL,
	QUANTITY    	INT NULL,
	ORDER_ID 	BIGINT REFERENCES ORDERS(ORDER_ID)
);
-------------------------------------------------------------------------------------------
CREATE TABLE OFFERS(
	OFFER_ID        BIGINT PRIMARY KEY AUTO_INCREMENT,
	NAME  	        VARCHAR(100) NOT NULL,
	EMAIL      	VARCHAR(60) NOT NULL,
	TEXT       	TEXT NULL
);

INSERT INTO OFFERS(NAME, EMAIL, TEXT) VALUES('Offer1', 'offer@gmail.com', '');
INSERT INTO OFFERS(NAME, EMAIL, TEXT) VALUES('Offer2', 'offer@gmail.com', '');
INSERT INTO OFFERS(NAME, EMAIL, TEXT) VALUES('Offer3', 'offer@gmail.com', '');
INSERT INTO OFFERS(NAME, EMAIL, TEXT) VALUES('Offer4', 'offer@gmail.com', '');
INSERT INTO OFFERS(NAME, EMAIL, TEXT) VALUES('Offer5', 'offer@gmail.com', '');
INSERT INTO OFFERS(NAME, EMAIL, TEXT) VALUES('Offer6', 'offer@gmail.com', '');
INSERT INTO OFFERS(NAME, EMAIL, TEXT) VALUES('Offer7', 'offer@gmail.com', '');